server:
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:db1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true